#!/bin/bash
#java -cp Courses/cse591/cse591_workspace/cse591/target/cse591-0.0.1-SNAPSHOT.jar functions.Batch_Inserter "LoadGraph" "citeseerx"
java -cp Courses/cse591/cse591_workspace/cse591/target/cse591-0.0.1-SNAPSHOT.jar functions.Batch_Inserter "LoadGraph" "Patents"
#java -cp Courses/cse591/cse591_workspace/cse591/target/cse591-0.0.1-SNAPSHOT.jar functions.Batch_Inserter "LoadGraph" "go_uniprot"
#java -cp Courses/cse591/cse591_workspace/cse591/target/cse591-0.0.1-SNAPSHOT.jar functions.Batch_Inserter "LoadGraph" "uniprotenc_150m"
